import { Inter } from "next/font/google"
import "../globals.css";

import DesktopNavbar from "@/components/sections/DesktopNavbar"
import MobileNavbar from "@/components/sections/MobileNavbar"
import Topbar from "@/components/sections/Topbar"
import { ClerkProvider } from "@clerk/nextjs";
import SuggestionBar from "@/components/sections/SuggestionBar";
import { Suspense } from "react";
import { PageSkeleton } from "@/components/skeletons/PageSkeleton";

export const metadata = {
  title: "UltraThreads",
  description: "Generated by Shreyash",
}

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
        <Topbar/>
        <main className="flex flex-row">
        <Suspense fallback={<p>Loading feed...</p>}>
          <DesktopNavbar/>
          <section className="main-container">
            <div className="w-full max-w-4xl">
            <Suspense fallback={<PageSkeleton/>}>
              {children}</Suspense>  
            </div>
          </section>
          <SuggestionBar/>
        </Suspense>
        </main>
        <MobileNavbar/>
      </body>
    </html>
    </ClerkProvider>
  )
}
